sources:
  - name: Supergraph
    handler:
      supergraph:
        source: ./supergraph.graphql
#      supergraph:
#        source: '{env.HIVE_CDN_URL}'
#        schemaHeaders:
#          X-Hive-CDN-Key: '{env.HIVE_CDN_KEY}'
#plugins:
#  - hive:
#      token: '{env.HIVE_TOKEN}'
